# Generated by Django 5.2.3 on 2025-06-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
    ]
