# Generated by Django 5.2.3 on 2025-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionVuelos", "0002_passenger_flight_seat_reservation_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="barcode",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
