# Generated by Django 5.2.3 on 2025-07-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionVuelos", "0003_alter_ticket_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="plane",
            name="manufacturer",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
    ]
