# Generated by Django 5.2.3 on 2025-07-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionVuelos", "0004_plane_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="document_type",
            field=models.CharField(
                choices=[("DNI", "DNI"), ("Pasaporte", "Pasaporte")],
                default="DNI",
                max_length=50,
            ),
        ),
    ]
