# Generated by Django 5.2.3 on 2025-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionVuelos", "0006_passenger_user_alter_reservation_reservation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="plane",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plane",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plane",
            name="duration_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plane",
            name="name",
            field=models.CharField(default="avion generico", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plane",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
