# Generated by Django 5.2.3 on 2025-08-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionVuelos",
            "0007_plane_active_plane_description_plane_duration_days_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plane",
            name="active",
        ),
        migrations.RemoveField(
            model_name="plane",
            name="available_seats",
        ),
        migrations.RemoveField(
            model_name="plane",
            name="description",
        ),
        migrations.RemoveField(
            model_name="plane",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="plane",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plane",
            name="price",
        ),
    ]
