# Generated by Django 5.2.3 on 2025-08-07 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionVuelos",
            "0008_remove_plane_active_remove_plane_available_seats_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plane",
            name="manufacturer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="gestionVuelos.flight",
            ),
        ),
    ]
