# Generated by Django 5.2.3 on 2025-08-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionVuelos", "0009_alter_plane_manufacturer_alter_reservation_flight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={"ordering": ["row", "column"]},
        ),
        migrations.AddField(
            model_name="seat",
            name="emergency_exit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seat",
            name="extra_legroom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("window", "Window"),
                    ("middle", "Middle"),
                    ("aisle", "Aisle"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("plane", "number")},
        ),
    ]
