# Generated by Django 5.2.3 on 2025-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionVuelos", "0010_alter_seat_options_seat_emergency_exit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name="seat",
            name="emergency_exit",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="extra_legroom",
        ),
    ]
