# Generated by Django 5.2.3 on 2025-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionVuelos",
            "0011_alter_seat_options_alter_seat_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="reserved",
                max_length=20,
            ),
        ),
    ]
